version: '3'

services:
  cfgsvr2:
    container_name: cfgsvr2-yh-test
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - cfgsvr2-yh-test:/data/db

volumes:
  cfgsvr2-yh-test: {}
